import test from 'node:test';
import assert from 'node:assert/strict';
import {Game,distance} from '../engine.js';
import {CAT_VASE} from '../cat.js';
const tick=(g,s,input={})=>{for(let i=0;i<Math.ceil(s/.05);i++)g.tick(.05,input);};
function near(){const g=new Game();g.start();g.player={x:3,z:7};return g;}
test('猫在视野附近跟随，停下会蹭腿，走开仍可自由移动',()=>{const g=near();tick(g,3);assert.equal(g.cat.state,'rub');assert.ok(distance(g.cat,g.player)<1);const z=g.player.z;for(let i=0;i<10;i++){g.move(1,0,.05);g.tick(.05);}assert.ok(g.player.x>3.6);assert.equal(g.cat.state,'follow');assert.equal(g.player.z,z);});
test('安抚给出呼噜和安静时间，门比更远的猫优先',()=>{const g=near();tick(g,2);g.action();assert.equal(g.cat.state,'calm');assert.ok(g.events.some(e=>e.kind==='catPurr'));const p={x:g.cat.x,z:g.cat.z};g.player={x:3,z:8};tick(g,10);assert.equal(g.cat.state,'calm');assert.equal(distance(g.cat,p),0);g.player={x:3,z:11};g.cat={...g.cat,x:4.2,z:11,state:'follow'};g.action();assert.equal(g.mode.type,'door');});
test('猫不透过门追踪，不穿墙和家具，玩家无需把猫推开',()=>{const g=near();g.player={x:3,z:11};tick(g,5);assert.equal(g.cat.state,'idle');assert.equal(g.cat.z,5.5);g.doors[0].open=true;g.doors[0].progress=1;g.player={x:3,z:9};for(let i=0;i<100;i++){g.tick(.05);assert.ok(g.canOccupy(g.cat.x,g.cat.z));}assert.ok(g.cat.z>7);g.cat.x=g.player.x;g.cat.z=g.player.z;assert.ok(g.canOccupy(g.player.x,g.player.z));});
test('猫寻路以自身为起点，关门不可通过，家长路径不被覆盖',()=>{const g=near(),p=structuredClone(g.parent);g.doors[0].open=false;const path=g.pathTo({x:3,z:12},g.cat,true);assert.ok(path.every(n=>n.z<10));assert.deepEqual(g.parent,p);});
test('玩具落在可达空地，引走后玩耍，有冷却且不罚噪声分',()=>{const g=near();tick(g,1);assert.equal(g.tossCatToy(0,-1),true);assert.equal(g.cat.state,'toy');assert.ok(g.canOccupy(g.cat.toy.x,g.cat.toy.z));assert.equal(g.tossCatToy(0,-1),false);tick(g,4);assert.equal(g.cat.state,'play');assert.equal(g.metrics.noiseBurden,0);assert.ok(g.cat.distractions===1);});
function vase(){const g=near();g.player={x:10.5,z:4};g.cat={...g.cat,x:10.5,z:3.3,state:'follow'};return g;}
test('扑花瓶先蓄势，可安抚、玩具或退开中断',()=>{for(const action of['pet','toy','leave']){const g=vase();tick(g,1);assert.equal(g.cat.state,'prepare');assert.ok(g.cat.timer>2);if(action==='pet')assert.ok(g.petCat());if(action==='toy')assert.ok(g.tossCatToy(0,1));if(action==='leave')g.player={x:3,z:12};tick(g,5);assert.equal(g.vase,'stable');assert.equal(g.mode,null);}});
test('蓄势结束触发一次接花瓶，失败声音来自花瓶，不直接判负',()=>{const g=vase();tick(g,5);assert.equal(g.mode?.type,'catch');assert.equal(g.cat.jumpUsed,true);assert.deepEqual(g.mode.noiseSource,CAT_VASE);g.resolveIncident(false);assert.equal(g.vase,'fallen');assert.deepEqual(g.noiseAt,CAT_VASE);assert.equal(g.status,'playing');const count=g.metrics.incidents;tick(g,20);assert.equal(g.metrics.incidents,count);});
test('猫引起的花瓶可以接住，现有评分与恢复搜索保持一致',()=>{const g=vase();tick(g,5);g.resolveIncident(true);assert.equal(g.vase,'caught');assert.equal(g.metrics.catches,1);tick(g,1);assert.equal(g.mode,null);});
test('玩家操作时冻结起跳预警，暂停冻结猫和玩具',()=>{const g=vase();tick(g,1);const timer=g.cat.timer;g.mode={type:'search',elapsed:0,spot:g.spots[0]};tick(g,1);assert.equal(g.cat.timer,timer);g.active=false;const c=structuredClone(g.cat);tick(g,1);assert.deepEqual(g.cat,c);});
test('存档保留安抚、玩具、蓄势及一次性事件，旧档自动补猫',()=>{for(const state of['calm','prepare','play']){const g=vase();g.cat.state=state;g.cat.timer=2;g.cat.jumpUsed=true;const h=new Game();assert.ok(h.restore(g.serialize()));assert.equal(h.cat.state,state);assert.equal(h.cat.timer,2);assert.equal(h.cat.jumpUsed,true);}const g=near();g.tossCatToy(0,-1);const h=new Game();assert.ok(h.restore(g.serialize()));assert.equal(h.cat.state,'toy');assert.ok(h.cat.route.length);const old=g.serialize();delete old.cat;assert.ok(h.restore(old));assert.equal(h.cat.state,'idle');old.cat={x:0,z:0};assert.ok(h.restore(old));assert.equal(h.cat.x,3);});
