import {finishRescue} from './rescue-helper.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import {Game,PRESETS} from '../engine.js';
import {INCIDENTS,incidentRoll,CATCH_INTRO} from '../incidents.js';
const tick=(g,t)=>{for(let n=0;n<t;n+=.02)g.tick(.02);};
function searching(id,seed=4){const g=new Game(1);g.start();g.seed=seed;g.night.unlocked=['kitchen-search','storage-search'];const s=g.spots.find(s=>s.id===id);g.player=id==='kitchen-search'?{x:21,z:2}:id==='study-search'?{x:16,z:1.8}:{x:21.5,z:10};g.action();assert.equal(g.mode?.spot,s);return g;}
test('评分满分必须完成返程，探索和等待不降低表现',()=>{const g=new Game();g.start();assert.equal(g.performance().rows[0].points,0);g.hasDevice=true;g.checkWin();assert.equal(g.performance().total,100);assert.equal(g.performance().grade,'S');g.time+=1000;g.realTime+=1000;assert.equal(g.performance().total,100);});
test('声响、错误落脚、失手、被看见均按行为计分，分数有界',()=>{const g=new Game();g.start();g.mode={type:'step',target:{x:3,z:11},elapsed:1};g.pointer=.99;g.pressSpace();assert.equal(g.metrics.steps,1);assert.equal(g.metrics.goodSteps,0);assert.equal(g.metrics.loudSounds,1);assert.equal(g.performance().rows[2].points,0);g.hasDevice=true;g.checkWin();assert.ok(g.performance().total<100);g.metrics.noiseBurden=10000;g.metrics.exposures=50;assert.ok(g.performance().total>=40);assert.equal(g.performance().rows[1].points,0);assert.equal(g.performance().rows[3].points,0);});
test('开门表现按实际施力时长计算，停下不会扣分',()=>{const g=new Game();g.start();g.player={x:3,z:11};g.action();g.tick(.05,{e:true});const before={...g.metrics};tick(g,2);assert.equal(g.metrics.doorSeconds,before.doorSeconds);g.tick(.05,{doorPush:.5});assert.equal(g.metrics.doorSeconds,.1);assert.ok(g.metrics.quietDoorSeconds>=.05&&g.metrics.quietDoorSeconds<.075);assert.ok(g.performance().rows[2].points>0&&g.performance().rows[2].points<25);});
test('地板判定区间缩窄，旧亮区边缘现在会踩响',()=>{assert.deepEqual(PRESETS.map(p=>p.width),[.22,.16,.16]);const g=new Game(1);g.start();g.mode={type:'step',target:{x:3,z:11},elapsed:0};g.pointer=.60;g.pressSpace();assert.equal(g.noise,50);});
test('三种搜索意外均能触发，准备段不会被提前按键跳过',()=>{for(const id of ['kitchen-search','study-search','storage-search']){const g=searching(id);tick(g,2.3);assert.equal(g.mode?.incidentId,id);assert.equal(g.metrics.incidents,1);g.pointer=.5;g.pressSpace();assert.equal(g.mode.type,'catch');tick(g,CATCH_INTRO);g.pointer=.5;g.pressSpace();assert.equal(g.mode.type,'catch');finishRescue(g);assert.equal(g.mode.type,'reaction');assert.equal(g.metrics.catches,1);tick(g,1.3);assert.equal(g.mode.type,'search');tick(g,4);assert.equal(g.spots.find(s=>s.id===id).searched,true);assert.equal(g.metrics.incidents,1);}});
test('随机结果固定，取消与刷新不会重抽，未触发事件不扣动作分',()=>{const id='study-search',g=searching(id,11);assert.ok(incidentRoll(g.seed,id)>=INCIDENTS[id].chance);tick(g,2.4);assert.equal(g.mode.type,'search');g.cancel();g.action();const h=new Game();assert.equal(h.restore(g.serialize()),true);h.active=true;tick(h,2.4);assert.equal(h.mode.type,'search');assert.equal(h.metrics.incidents,0);assert.equal(h.performance().rows[2].points,25);});
test('慢动作按真实时间判定，世界继续放慢运行，暂停冻结所有计时',()=>{const g=searching('kitchen-search');tick(g,2.3);const a=g.time,b=g.realTime;tick(g,1);assert.ok(g.time-a<.13);assert.ok(g.realTime-b>=.99);const m=structuredClone(g.mode);g.active=false;tick(g,3);assert.deepEqual(g.mode,m);g.active=true;tick(g,5);assert.equal(g.incidentOutcomes['kitchen-search'],'fallen');assert.equal(g.metrics.catches,0);assert.ok(g.events.some(e=>e.kind==='metalDrop'));assert.equal(g.status,'playing');});
test('接物中途保存恢复时机、概率、评分与搜索进度，不重复加分',()=>{const g=searching('storage-search');tick(g,3.3);const h=new Game();assert.equal(h.restore(JSON.parse(JSON.stringify(g.serialize()))),true);assert.equal(h.mode.elapsed,g.mode.elapsed);assert.equal(h.mode.rescue.handX,g.mode.rescue.handX);assert.equal(h.mode.rescue.stage,g.mode.rescue.stage);assert.equal(h.mode.rescue.left,0);assert.equal(h.mode.rescue.grace,.65);assert.deepEqual(h.metrics,g.metrics);assert.equal(h.seed,g.seed);h.active=true;finishRescue(h);h.pressSpace();assert.equal(h.metrics.catches,1);const j=new Game();assert.equal(j.restore(h.serialize()),true);j.active=true;tick(j,1.3);assert.equal(j.mode?.type,'search');assert.ok(j.mode.elapsed>2);});
test('放弃接物只落地一次，结果期间可取消自动继续搜索',()=>{const g=searching('kitchen-search');tick(g,2.3);g.cancel();assert.equal(g.mode.type,'reaction');assert.equal(g.metrics.loudSounds,0);tick(g,.55);assert.equal(g.metrics.loudSounds,1);g.cancel();tick(g,1.3);assert.equal(g.mode,null);assert.equal(g.metrics.loudSounds,1);});
test('兼容旧 v4 进度并明确评分从续玩后开始统计',()=>{const g=new Game();g.start();tick(g,3);const save=g.serialize();delete save.metrics;delete save.seed;delete save.incidentUsed;delete save.incidentOutcomes;delete save.realTime;const h=new Game();assert.equal(h.restore(save),true);assert.equal(h.performance().partial,true);assert.equal(h.realTime,save.time);});

test('不可移动的特写期间暂缓识别，结束后恢复原有发现规则',()=>{const g=new Game(1);g.start();g.player={x:3,z:9};g.parent={...g.parent,state:'checking',phase:'scan',x:3,z:8,heading:0,scanHeading:0,timer:20};g.beginIncident('kitchen-search');for(let i=0;i<600&&g.mode;i++)g.tick(.02);assert.equal(g.status,'playing');assert.equal(g.mode,null);g.parent.heading=0;g.parent.scanHeading=0;g.parent.timer=2.6;tick(g,.3);assert.equal(g.status,'lost');});
