import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {floorAt} from '../surfaces.js';
import {acousticProfile} from '../spatial-audio.js';
import {Game} from '../engine.js';
test('材质覆盖实际地毯边界、餐厅瓷砖和洗衣间；木板陷阱不变',()=>{assert.equal(floorAt(3.65,12.15),'carpet');assert.equal(floorAt(4.4,12.15),'wood');assert.equal(floorAt(2.6,2.8),'carpet');assert.equal(floorAt(21,3),'tile');assert.equal(floorAt(12,16),'tile');assert.equal(floorAt(16,3),'wood');assert.equal(floorAt(3,9),'wood');});
test('源在世界中固定，转头会翻转左右与前后；距离和遮挡有不同反馈',()=>{const a={x:0,z:0},b={x:3,z:-3};assert.equal(acousticProfile(b,a,0).direction,'右前方');assert.equal(acousticProfile(b,a,Math.PI).direction,'左后方');assert.equal(acousticProfile({x:0,z:-1},a).range,'很近');assert.equal(acousticProfile({x:0,z:-10},a).range,'远处');assert.equal(acousticProfile(b,a).cutoff,undefined);});
test('玩家和父母声源发出时携带真实所在的地板材质',()=>{const g=new Game();g.emit('parentStep',40,3.65,12.15);g.emit('step',3,21,3);assert.equal(g.events[0].surface,'carpet');assert.equal(g.events[1].surface,'tile');});
test('12 个实录切片是有效单声道 PCM，起止淡出且不削波',()=>{for(const surface of['wood','tile','carpet'])for(let i=1;i<=4;i++){const b=readFileSync(new URL(`../../assets/audio/step-${surface}-${i}.wav`,import.meta.url));assert.equal(b.toString('ascii',0,4),'RIFF');assert.equal(b.readUInt16LE(22),1);assert.equal(b.readUInt32LE(24),32000);let max=0;for(let n=44;n<b.length;n+=2)max=Math.max(max,Math.abs(b.readInt16LE(n)));assert.ok(max>1000&&max<24000);assert.equal(b.readInt16LE(44),0);assert.equal(b.readInt16LE(b.length-2),0);}});
