"""Measure RMS energy in <400 / 400–2300 / >2300 Hz, Hann-windowed FFT.
Door impact measures the audible 0.305–0.645 s segment. Source files are local mono PCM; generated levels support approximate masking, not SPL calibration.
"""
import wave, math, cmath, pathlib, json
root=pathlib.Path(__file__).resolve().parents[2]
def fft(a):
 n=len(a);j=0
 for i in range(1,n):
  bit=n>>1
  while j&bit:j^=bit;bit>>=1
  j^=bit
  if i<j:a[i],a[j]=a[j],a[i]
 size=2
 while size<=n:
  w=cmath.exp(-2j*math.pi/size)
  for i in range(0,n,size):
   phase=1
   for j in range(size//2):
    u=a[i+j];v=a[i+j+size//2]*phase;a[i+j]=u+v;a[i+j+size//2]=u-v;phase*=w
  size*=2
 return a
levels={}
for path in sorted((root/'assets/audio').glob('*.wav')):
 with wave.open(str(path),'rb') as f:
  import array
  samples=array.array('h',f.readframes(f.getnframes()));rate=f.getframerate()
 if path.stem=='door-bump':samples=samples[round(.305*rate):round(.645*rate)]
 n=2048;window=[.5-.5*math.cos(2*math.pi*i/(n-1)) for i in range(n)];energy=[0,0,0];count=0
 for start in range(0,len(samples)-n+1,n):
  freq=fft([samples[start+i]/32768*window[i] for i in range(n)])
  for i,z in enumerate(freq[:n//2+1]):energy[0 if i*rate/n<400 else 1 if i*rate/n<2300 else 2]+=abs(z)**2*(1 if i in (0,n//2) else 2)
  count+=1
 levels[path.stem]=[round(math.sqrt(e/max(1,count)/(n*sum(w*w for w in window))),6) for e in energy]
(root/'source/sample-bands.js').write_text('// Generated by tools/measure-audio-bands.py; normalized digital RMS, not physical SPL.\nexport const SAMPLE_BANDS='+json.dumps(levels,indent=2)+';\n')
print(json.dumps({k:v for k,v in levels.items() if k in ['floor-creak-1','snore-real','washer-spin','step-wood-1']},indent=2))
